apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.service.type: ClusterIP
    kompose.service.updateStrategy: RollingUpdate
    kompose.version: 1.25.0 (a70f80cc)
  creationTimestamp: null
  labels:
    io.kompose.service: senders-api
  name: senders-api
  namespace: squidgames
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: senders-api
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.service.type: ClusterIP
        kompose.service.updateStrategy: RollingUpdate
        kompose.version: 1.25.0 (a70f80cc)
      creationTimestamp: null
      labels:
        io.kompose.service: senders-api
    spec:
      containers:
        - image: gcr.io/mi-propject2/rabbitsenderv1:latest
          name: senders-api
          ports:
            - containerPort: 3005
          resources: {}
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.service.type: ClusterIP
    kompose.service.updateStrategy: RollingUpdate
    kompose.version: 1.25.0 (a70f80cc)
  creationTimestamp: null
  labels:
    io.kompose.service: senders-api-tcp
  name: senders-api-tcp
  namespace: squidgames
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    io.kompose.service: senders-api
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: networking.k8s.io/v1 
kind: Ingress 
metadata: 
  name: balance-sopes1
  namespace: squidgames
  annotations:
    traefik.ingress.kubernetes.io/affinity: "true"
    kubernetes.io/ingress.class: nginx 
    nginx.ingress.kubernetes.io/rewrite-target: / 
    nginx.ingress.kubernetes.io/service-upstream: "true"
spec: 
  rules: 
  - host: 34.69.94.228.nip.io
    http:
      paths:
      - path: "/" 
        pathType: Prefix 
        backend: 
          service:
            name: senders-api-tcp 
            port: 
              number: 80