apiVersion: networking.k8s.io/v1beta1 
kind: Ingress 
metadata: 
  name: balance-sopes1
  namespace: squidgames
  annotations:
    kubernetes.io/ingress.class: "gce"
    traefik.ingress.kubernetes.io/affinity: "true"
    nginx.ingress.kubernetes.io/rewrite-target: / 
    nginx.ingress.kubernetes.io/service-upstream: "true"
spec: 
  rules: 
  - http:
      paths:
      - path: "/" 
        pathType: Prefix 
        backend: 
          serviceName: senders-api-tcp 
          servicePort: 80