apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.service.type: ClusterIP
    kompose.service.updateStrategy: RollingUpdate
    kompose.version: 1.25.0 (a70f80cc)
  creationTimestamp: null
  labels:
    io.kompose.service: senders-api-tcp
  name: senders-api-tcp
  namespace: squidgames
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    io.kompose.service: senders-api
  type: ClusterIP
status:
  loadBalancer: {}
